### ISSUE TITLE
How do I see the creator (owner) of a server?

### ISSUE THREAD

**Issue by reinhard76** [ibm-cloud-docs/virtual-servers#10]
Question
How can I see the creator of a virtual or bare metal server?

Answer
While the information is displayed on the server list, you can use ibmcloud CLI commands to show who created a server. 

For virtual servers:
ibmcloud sl vs list --column id --column hostname --column datacenter --column tags --column cpu --column memory --column created_by

For bare metal servers:
ibmcloud sl hardware list --column id --column hostname --column datacenter --column tags --column status --column cpu --column memory --column created_by

For information on the ibmcloud CLI, please refer to https://cloud.ibm.com/docs/cli?topic=cli-getting-started

**Comment by jmilst** [comment]
closing because internal issues aren't supposed to be in this public facing repo - added to backlog
