### ISSUE TITLE
'download OS iso'

### ISSUE THREAD

**Issue by LiamHarpur** [ibm-cloud-docs/virtual-servers#12]
Sometimes customers ask about getting the IBM ISOs for the OS images we provide e.g.:
"Please give me the ISO that is used to create this deployed VSI"

Please update the documentation  e.g. "IBM does not provide the ...."

**Comment by HarpurLiam** [comment]
Please add this new information on what IBM does not provide regarding ISOs to this topic on Public Images: Getting started with image templates > Public Images Ref.: https://cloud.ibm.com/docs/image-templates?topic=image-templates-getting-started-with-image-templates#public-images

**Comment by jmilst** [comment]
closing because internal issues aren't supposed to be in this public facing repo - added to backlog
