### ISSUE TITLE
broken link in https://cloud.ibm.com/docs/virtual-servers?topic=virtual-servers-faqs-virtual-servers#what-types-of-virtual-servers-are-available-for-use-

### ISSUE THREAD

**Issue by LiamHarpur** [ibm-cloud-docs/virtual-servers#16]
broken link in https://cloud.ibm.com/docs/virtual-servers?topic=virtual-servers-faqs-virtual-servers#what-types-of-virtual-servers-are-available-for-use-

... that points to the following (the following does not exist)

https://cloud.ibm.com/docs/virtual-servers?topic=virtual-servers-capacity-considerations

**Comment by jmilst** [comment]
closing because internal issues aren't supposed to be in this public facing repo - added to backlog
