### ISSUE TITLE
Is the page for Virtual Server Instance SSD updated with the latest information.

### ISSUE THREAD

**Issue by davidyap7** [ibm-cloud-docs/virtual-servers#17]
Regarding this documentation page for Virtual Server Instance SSD https://cloud.ibm.com/docs/virtual-servers?topic=virtual-servers-about-virtual-server-profiles#SSD . One of the data center that is being offering this service is shown as Melbourne (MEL01). Melbourne (MEL01) has been closed since 2020 but is still reflecting on this page. Would like to confirm if the data centers shown on this page is correct and updated with the latest list of data centers that are offering this service.

**Comment by jmilst** [comment]
closing because internal issues aren't supposed to be in this public facing repo - added to backlog
