### ISSUE TITLE
Incorrect link for KVM access

### ISSUE THREAD

**Issue by frykshon** [ibm-cloud-docs/virtual-servers#19]
The 'Connecting to the KVM console' section doesn't explain how to connect to the kvm. The link in the tip section that wold lead you to docs explaining how to connect is not working either. 

Specific section of the doc:
https://cloud.ibm.com/docs/virtual-servers?topic=virtual-servers-managing-virtual-servers#kvm-console

Currently the tip reads:

>If you have issues with incompatible Java settings in your browser, you can alternatively use the TightVNC viewer. You must download and install TightVNC viewer for Windows 64-bit version. For more information, see How to connect to KVM console of IBM Cloud Virtual Servers from the Support Center.

And currently links to:
https://www.ibm.com/support/pages/how-connect-kvm-console-ibm-cloud-virtual-servers

I believe it should link to this documentation instead:
https://cloud.ibm.com/docs/virtual-servers?topic=virtual-servers-access-kvm-console

**Comment by gudrun-wolfgram** [comment]
@frykshon - Thanks for noticing and submitting this issue. I've updated the content with the link to the current information in Accessing the KVM console for virtual servers.
