### ISSUE TITLE
Broken link in doc page

### ISSUE THREAD

**Issue by DougAtIBM** [ibm-cloud-docs/virtual-servers#2]
This page 
https://cloud.ibm.com/docs/virtual-servers?topic=virtual-servers-faq-image-templates 
has a link that does not point to the correct place. Instead of showing the list of supported operating systems that can be used in a custom generated ISO it lands on a generic cloud marketing page.

This tip on the page point to non-existing file:
Only IBM Cloud supported operating systems can be used to load an ISO template onto an instance. For more information, see Supported Operating Systems. See attached image.

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/18483022/92218152-f7ea7980-ee98-11ea-82c1-b64176396be7.png">

**Comment by bpersich** [comment]
I updated the link to point to:
https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-about-software&locale=en#supported-operating-systems-for-ibm-cloud-virtual-servers
