### ISSUE TITLE
Nessus Vulnerability Assessment & Reporting product EOL 

### ISSUE THREAD

**Issue by RZurchin** [ibm-cloud-docs/virtual-servers#3]
The Nessus Vulnerability Assessment & reporting offering was deprecated 07/29/2020.  There is not an integrated alternative at this time.  Customers that require this service need to go direct with a 3rd party that meets their needs. 

[Nessus Deprecation FAQ_R2.docx](https://github.com/ibm-cloud-docs/virtual-servers/files/5356042/Nessus.Deprecation.FAQ_R2.docx)

**Comment by bpersich** [comment]
Removed references to Nessus. 

Thanks for your input.
