### ISSUE TITLE
Auto-scaling Documentation is not updated and lack uniformity

### ISSUE THREAD

**Issue by bibhubhusan** [ibm-cloud-docs/virtual-servers#5]
The schedule-based scaling & resource-based scaling pages has the same content. It seems the resource-based scaling page is not updated propoerly.

https://cloud.ibm.com/docs/virtual-servers?topic=virtual-servers-about-auto-scale
https://cloud.ibm.com/docs/virtual-servers?topic=virtual-servers-managing-schedule-based-auto-scaling
https://cloud.ibm.com/docs/virtual-servers?topic=virtual-servers-managing-resourced-based-auto-scaling

**Comment by sg-gs** [comment]
Hey, @DLM-IBM something new here? Trying to learn how to auto-scale a group of VM but lacking good docs providing some context. Documentation about this topic seems outdated.

**Comment by gudrun-wolfgram** [comment]
@bibhubhusan and @sg-gs 

Are you looking for Auto Scale for VPC information? The above links are for classic infrastructure virtual server auto scaling. 

Here is a link to the information for Auto Scale for VPC:

**Creating an instance group for auto scaling**
https://cloud.ibm.com/docs/vpc?topic=vpc-creating-auto-scale-instance-group

**FAQs for auto scale**
https://cloud.ibm.com/docs/vpc?topic=vpc-faqs-auto-scale
